development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: clever
  pool: 5
  username: root
  password: root
  host: localhost
  port: 3306

#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: clever
#  pool: 5
#  username: root
#  password: root
#  host: localhost
#  port: 3306