# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71fd7ada835c96867aee4772c6492ad62afdf453a3cfc2e68b6c8ab79cc99ec08e4d222841d6e83c9b5e87245ef16555a359bd683200e88341ba4b0039ac659a

test:
  secret_key_base: 01dd4865d39f4e505b8a6f243c8a7ee050b2ee0795f256719d0aafa4e9d715b0363a71604389379d4cdc4cced436b7759dca2d08e39d4773039e6eb6b2b0e463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
